/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprestamos;


import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javazoom.jl.player.Player;

/**
 *
 * @author Sergio
 */
public class Prestamos extends javax.swing.JFrame {
    String prueba;
      int cantidadPrestamo, sueldoMensual, añosPrestamo ;
      double cantidadMasInteres;
      double mensualidadPrestamo,viabilidad;
       double PORCENTAJE_INTERES;
       boolean botonesPrestamo;
    private Object evt;

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        
        getRootPane().setDefaultButton(calcular);
        
        Calendar cal = Calendar.getInstance();
            DateFormat formateadorFechaLarga = DateFormat.getDateInstance(DateFormat.MEDIUM);
                System.out.println(formateadorFechaLarga.format(cal.getTime()));
                jLabelFecha.setText(String.valueOf(formateadorFechaLarga.format(cal.getTime())));
         
         DateFormat formateadorHoraCorta = DateFormat.getTimeInstance(DateFormat.SHORT);
            System.out.println(formateadorHoraCorta.format(cal.getTime()));
            jLabelHora.setText(String.valueOf(formateadorHoraCorta.format(cal.getTime())));
         
        jLabelPrestamoConcedido.setVisible(false);
        datosPrestamo.setVisible(false);
        jLabelCantidad.setVisible(false);
        totalPrestamo.setVisible(false);
        jLabelPorcentaje.setVisible(false);
        simboloPorcentaje.setVisible (false);
        interes.setVisible(false);
        jLabelMensualidad.setVisible(false);
        mensualidad.setVisible(false);
        jLabelAños.setVisible(false);
        aceptar.setVisible(false);
        cancelar.setVisible(false);
        añosAPagar.setVisible(false);
       
       
        setLocationRelativeTo(null);
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/p.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPrincipal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        años = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sueldo = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCantidad = new javax.swing.JLabel();
        totalPrestamo = new javax.swing.JLabel();
        jLabelPorcentaje = new javax.swing.JLabel();
        interes = new javax.swing.JLabel();
        jLabelMensualidad = new javax.swing.JLabel();
        mensualidad = new javax.swing.JLabel();
        jLabelAños = new javax.swing.JLabel();
        añosAPagar = new javax.swing.JLabel();
        datosPrestamo = new javax.swing.JLabel();
        jLabelPrestamoConcedido = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        simboloPorcentaje = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloPrincipal.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tituloPrincipal.setText("            Solicita tu Prestamo");
        tituloPrincipal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cantidad a solicitar");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Número de años");

        años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Sueldo mensual");

        sueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoActionPerformed(evt);
            }
        });

        calcular.setBackground(new java.awt.Color(255, 210, 180));
        calcular.setText("Calcular");
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidad.setText("Cantidad total del prestamo:");

        totalPrestamo.setText("______");

        jLabelPorcentaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPorcentaje.setText("Porcentaje de interés:");

        interes.setText("______");

        jLabelMensualidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensualidad.setText("Pago mensual:");

        mensualidad.setText("______");

        jLabelAños.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAños.setText("Mensualidades:");

        añosAPagar.setText("______");

        datosPrestamo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        datosPrestamo.setText("Datos del prestamo");

        jLabelPrestamoConcedido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrestamoConcedido.setForeground(new java.awt.Color(248, 140, 64));
        jLabelPrestamoConcedido.setText("¡Su préstamo ha sido concedido!");

        aceptar.setBackground(new java.awt.Color(0, 0, 0));
        aceptar.setForeground(new java.awt.Color(239, 159, 93));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 0, 0));
        cancelar.setForeground(new java.awt.Color(239, 159, 93));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        simboloPorcentaje.setText("%");

        jLabelFecha.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelFecha.setText("jLabel4");

        jLabelHora.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelHora.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aceptar)
                                .addGap(98, 98, 98)
                                .addComponent(calcular))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMensualidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCantidad)
                                            .addComponent(jLabelPorcentaje)
                                            .addComponent(jLabelAños)
                                            .addComponent(datosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(añosAPagar)
                                            .addComponent(totalPrestamo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(interes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(simboloPorcentaje))
                                            .addComponent(mensualidad))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(años, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelHora)
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabelPrestamoConcedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloPrincipal)
                    .addComponent(jLabelFecha))
                .addGap(4, 4, 4)
                .addComponent(jLabelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrestamoConcedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(totalPrestamo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorcentaje)
                    .addComponent(interes)
                    .addComponent(simboloPorcentaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMensualidad)
                    .addComponent(mensualidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAños)
                    .addComponent(añosAPagar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añosActionPerformed

    private void sueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        
       
       
       
        
        /*he definido la variable de tipo int, pero el textField es de tipo String
        por lo que he buscado una manera de transformalo a int*/
        cantidadPrestamo = Integer.parseInt(cantidad.getText());
        sueldoMensual = Integer.parseInt(sueldo.getText());
        añosPrestamo = Integer.parseInt(años.getText());
        
        /*Aqui he utilizado el if para poner tres condiones para que me elija
        un porcentaje de interes segun la cantidad solicitada*/
        if(añosPrestamo < 3){
              PORCENTAJE_INTERES = 5;
        }else if(añosPrestamo < 7 && añosPrestamo > 3){
            PORCENTAJE_INTERES = 7;
        }else if(añosPrestamo < 10 && añosPrestamo > 7){
            PORCENTAJE_INTERES = 10;
        }else{
            PORCENTAJE_INTERES = 13;
        }
        
        
      
        
        
         calcularPrest(cantidadPrestamo,añosPrestamo,sueldoMensual);
       
       
       /*He puesto que la viabilidad sea mayor de 1 por que la mensualidad del
         prestamo tiene que ser menor que la mitad del sueldo del usuario, todo 
         numero inferior a 1 en las operaciones que realizamos, hace indicar que
         la mensualidad del prestamo es mayor que la mitad del sueldo*/
        if(viabilidad > 1){
         jLabelPrestamoConcedido.setVisible(true);
         datosPrestamo.setVisible(true);
         jLabelCantidad.setVisible(true);
         totalPrestamo.setVisible(true);
         jLabelPorcentaje.setVisible(true);
         simboloPorcentaje.setVisible (true);
         interes.setVisible(true);
         jLabelMensualidad.setVisible(true);
         mensualidad.setVisible(true);
         jLabelAños.setVisible(true);
         aceptar.setVisible(true);
         cancelar.setVisible(true);
         añosAPagar.setVisible(true);
         botonesPrestamo = true;
         aceptar.setText("Aceptar");
         cancelar.setText("Cancelar");
       
       DecimalFormat formato = new DecimalFormat("#,###.### ¤");
       DecimalFormat formato2 = new DecimalFormat("#.### ¤");
       
       totalPrestamo.setText(String.valueOf(formato.format(cantidadMasInteres)));
       interes.setText(String.valueOf(PORCENTAJE_INTERES));
       mensualidad.setText(String.valueOf(formato.format(mensualidadPrestamo)));
       añosAPagar.setText(Integer.toString(añosPrestamo * 12));
     
             
        }else{ 
         jLabelPrestamoConcedido.setVisible(true);
         jLabelPrestamoConcedido.setText("El Prestamo no cumple los requisitos.");
         datosPrestamo.setVisible(true);
         datosPrestamo.setText("");
         jLabelCantidad.setVisible(false);
         totalPrestamo.setVisible(false);
         jLabelPorcentaje.setVisible(false);
         simboloPorcentaje.setVisible (false);
         interes.setVisible(false);
         jLabelMensualidad.setVisible(false);
         mensualidad.setVisible(false);
         jLabelAños.setVisible(false);
         aceptar.setVisible(true);
         cancelar.setVisible(true);
         añosAPagar.setVisible(false);
         botonesPrestamo = false; 
         aceptar.setText("Volver a calcular");
         cancelar.setText("Salir");
         calcular.setVisible (false);
      
       
       
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      
      if(botonesPrestamo){
      DatosUsuario DatosUsuario = new DatosUsuario();  
      DatosUsuario.setVisible (true);
      }
      else{
       jLabelPrestamoConcedido.setVisible(false);
       datosPrestamo.setVisible(false);
       cantidad.setText("");
       años.setText("");
       sueldo.setText("");  
       aceptar.setVisible(false);
       cancelar.setVisible(false);
       calcular.setVisible (true);
      }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
     
           if(botonesPrestamo){
       calcular.setVisible (true);
       jLabelCantidad.setVisible(false);
       totalPrestamo.setVisible(false);
       jLabelPorcentaje.setVisible(false);
       simboloPorcentaje.setVisible (false);
       interes.setVisible(false);
       jLabelMensualidad.setVisible(false);
       mensualidad.setVisible(false);
       jLabelAños.setVisible(false);
       aceptar.setVisible(false);
       cancelar.setVisible(false);
       añosAPagar.setVisible(false);
       cantidad.setText("");
       años.setText("");
       sueldo.setText("");
       jLabelPrestamoConcedido.setVisible(false);
       datosPrestamo.setVisible(false);
          try {
             Player player = new Player(getClass().getResourceAsStream("/sonidos/sonidoError.mp3"));
                player.play();
                player.close();
         }      catch (Exception e) {
                  System.out.println("Error al reproducir el audio");
         } 

       
       
      }
      else{
      System.exit(0);
      }
    }//GEN-LAST:event_cancelarActionPerformed

    
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prestamos().setVisible(true);
           
              
        });
        
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField años;
    private javax.swing.JLabel añosAPagar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel datosPrestamo;
    private javax.swing.JLabel interes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAños;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelMensualidad;
    private javax.swing.JLabel jLabelPorcentaje;
    private javax.swing.JLabel jLabelPrestamoConcedido;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensualidad;
    private javax.swing.JLabel simboloPorcentaje;
    private javax.swing.JTextField sueldo;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JLabel totalPrestamo;
    // End of variables declaration//GEN-END:variables

 public void calcularPrest(int cantidad, int años, int sueldo){
     
     cantidadPrestamo = cantidad;
     añosPrestamo = años;
     sueldoMensual = sueldo;
     cantidadMasInteres = cantidadPrestamo * (PORCENTAJE_INTERES / 100 + 1);
        mensualidadPrestamo = cantidadMasInteres / (añosPrestamo * 12);
        viabilidad = (sueldoMensual / 2) / mensualidadPrestamo ;
        
        
   
 }




}

